import { SearchResult } from "./searchService";

export const exportToCSV = (results: SearchResult[], query: string) => {
  const headers = ['Source', 'ID', 'Title', 'Authors', 'Date', 'Abstract/Status', 'URL'];
  const csvRows = [headers.join(',')];

  results.forEach(result => {
    const row = [
      result.source,
      result.id,
      `"${result.title.replace(/"/g, '""')}"`,
      `"${(result.authors || '').replace(/"/g, '""')}"`,
      result.date || '',
      `"${((result.abstract || result.status || '').replace(/"/g, '""'))}"`,
      result.url
    ];
    csvRows.push(row.join(','));
  });

  const csvContent = csvRows.join('\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  
  link.setAttribute('href', url);
  link.setAttribute('download', `pharmaai-results-${query.replace(/\s+/g, '-')}-${Date.now()}.csv`);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

export const exportToPDF = async (
  query: string,
  results: SearchResult[],
  synthesis: string
) => {
  // Create HTML content for PDF
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>PharmaAI Research Report - ${query}</title>
      <style>
        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
          line-height: 1.6;
          color: #333;
          max-width: 800px;
          margin: 0 auto;
          padding: 40px 20px;
        }
        h1 {
          color: #2563eb;
          border-bottom: 3px solid #2563eb;
          padding-bottom: 10px;
        }
        h2 {
          color: #1e40af;
          margin-top: 30px;
          border-bottom: 1px solid #e5e7eb;
          padding-bottom: 5px;
        }
        .meta {
          color: #6b7280;
          font-size: 0.9em;
          margin-bottom: 30px;
        }
        .synthesis {
          background: #f3f4f6;
          padding: 20px;
          border-left: 4px solid #2563eb;
          margin: 20px 0;
        }
        .result {
          margin-bottom: 25px;
          padding: 15px;
          border: 1px solid #e5e7eb;
          border-radius: 8px;
        }
        .result-title {
          font-weight: 600;
          color: #1f2937;
          margin-bottom: 8px;
        }
        .result-meta {
          font-size: 0.85em;
          color: #6b7280;
          margin-bottom: 8px;
        }
        .result-abstract {
          color: #4b5563;
          font-size: 0.95em;
        }
        .badge {
          display: inline-block;
          padding: 3px 8px;
          background: #dbeafe;
          color: #1e40af;
          border-radius: 4px;
          font-size: 0.8em;
          font-weight: 500;
        }
        .footer {
          margin-top: 50px;
          padding-top: 20px;
          border-top: 1px solid #e5e7eb;
          text-align: center;
          color: #9ca3af;
          font-size: 0.85em;
        }
      </style>
    </head>
    <body>
      <h1>PharmaAI Research Report</h1>
      <div class="meta">
        <strong>Query:</strong> ${query}<br>
        <strong>Results:</strong> ${results.length} sources<br>
        <strong>Generated:</strong> ${new Date().toLocaleString()}
      </div>

      <h2>AI Synthesis</h2>
      <div class="synthesis">
        ${synthesis.split('\n\n').map(p => `<p>${p}</p>`).join('')}
      </div>

      <h2>Detailed Results</h2>
      ${results.map(result => `
        <div class="result">
          <span class="badge">${result.source}</span>
          <div class="result-title">${result.title}</div>
          <div class="result-meta">
            ${result.authors ? `<strong>Authors:</strong> ${result.authors}<br>` : ''}
            ${result.date ? `<strong>Date:</strong> ${result.date}<br>` : ''}
            ${result.phase ? `<strong>Phase:</strong> ${result.phase}<br>` : ''}
            ${result.status ? `<strong>Status:</strong> ${result.status}<br>` : ''}
            <strong>Link:</strong> <a href="${result.url}">${result.url}</a>
          </div>
          ${result.abstract ? `<div class="result-abstract">${result.abstract}</div>` : ''}
        </div>
      `).join('')}

      <div class="footer">
        Generated by PharmaAI - Biomedical Literature Synthesizer<br>
        Powered by Lovable Cloud
      </div>
    </body>
    </html>
  `;

  // Create blob and download
  const blob = new Blob([htmlContent], { type: 'text/html' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  
  link.setAttribute('href', url);
  link.setAttribute('download', `pharmaai-report-${query.replace(/\s+/g, '-')}-${Date.now()}.html`);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  // Note: For true PDF export, we'd need a library like jsPDF or server-side generation
  // This exports as HTML which can be printed to PDF by the browser
};
